buildVersion=3.0

accounts.message=Welcome to EazyBank accounts related local APIs
accounts.contractDetails.name=John Doe
accounts.contractDetails.email=john.doe@example.com
accounts.phone=0123456789,0987654321
