buildVersion=2.0

accounts.message=Welcome to EazyBank QA accounts related local APIs
accounts.contractDetails.name=QA
accounts.contractDetails.email=beanvn@gmail.com
accounts.phone=0123456789,0987654321
