buildVersion=1.0

accounts.message=Welcome to EazyBank Production accounts related APIs for Webhook Loc 2
accounts.contractDetails.name=production
accounts.contractDetails.email=production@gmail.com
accounts.phone=0989820167,0961204771
