spring.application.name=loans

buildVersion=1.0

loans.message=Welcome to EazyBank loans related local APIs
loans.contactDetails.name=Loans default
loans.contactDetails.email=loandefault@gmail.com
loans.phone=0123456789,0987654321

eureka.client.service-url.default-zone=http://eurekaserver:8761/eureka/
