buildVersion=1.0

loans.message=Welcome to EazyBank loans related Production APIs for RabbitMQ
loans.contactDetails.name=Loan Production
loans.contactDetails.email=laonproduction@gmail.com
loans.phone=0123456789,0987654321
